### PR TITLE
Upgrade version to 1.1.15

### PR DESCRIPTION
**Pull request by YangSan0622**
*Issue #, if available:*
N/A

*Description of changes:*
Upgrading version to 1.1.15 for release

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by YangSan0622** [comment]
The Windows build failure is not introduced by the PR, I have created a question in Github community https://github.com/orgs/community/discussions/49030 to get helps on this.

**Comment by blacktooth** [comment]
Did all the integration test succeed?

**Comment by YangSan0622** [comment]
Yes, all the integration test passed locally

**Review by blacktooth — APPROVED** [review]

**Comment by NersesAM** [comment]
here is a PR to fix build failures. https://github.com/awslabs/aws-glue-schema-registry/pull/251

**Pull request merged**
